apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.global.namespace }}
  name: mock-acd-nodejs
  annotations:
    Release.Name: {{ .Release.Name }}
    Release.Revision: "{{ .Release.Revision }}"
    Chart.Name: {{ .Chart.Name }}
    Chart.Version: {{ .Chart.Version }}
data:
  mode: prod
  rabbit-amqp: {{ .Values.global.rabbit.api.amqp }}
  messageRate: '10'
  exchangeName: {{ .Values.exports.api.global.acdExchangeName }}
  imports-rabbit-amqp: {{ .Values.imports.rabbit.api.amqp }}
  imports2-rabbit-amqp: {{ .Values.imports2.rabbit.api.amqp }}
